[package]
name = "twacqwq"
version = "0.1.0"
authors = ["twacqwq <xiaot.qaq@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"